export enum UserProfileValidationError {
  NO_USER_PROFILE_DATA,
  EMPTY_FIRST_NAME,
  EMPTY_LAST_NAME,
  EMPTY_USERNAME,
  AGE_IS_NOT_A_NUMBER,
  EMPTY_COUNTRY,
  EMPTY_CITY,
  EMPTY_CURRENCY,
  INTERNAL_SERVER_ERROR
}
